[package]
name = "rust_lang_concepts"
version = "0.1.0"
authors = ["Ameer Hamza <ameernormie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
